---
language: python
python: '2.7'
install:
- curl -O http://saucelabs.com/downloads/Sauce-Connect-latest.zip
- unzip Sauce-Connect-latest.zip
- java -jar Sauce-Connect.jar $SAUCE_USERNAME $SAUCE_ACCESS_KEY -f CONNECTED &
- JAVA_PID=$!
- mkdir -p buildout-cache/eggs
- mkdir -p buildout-cache/downloads
- python bootstrap.py -c travis.cfg
- bin/buildout -N -t 3 -c travis.cfg
before_script:
- bash -c "while [ ! -f CONNECTED ]; do sleep 2; done"
- export ROBOT_BUILD_NUMBER=travis-$TRAVIS_BUILD_NUMBER
- export ROBOT_REMOTE_URL=http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com:80/wd/hub
script: bin/test
after_script:
- kill $JAVA_PID
env:
  global:
  - secure: ! 'FK96u1tPogYIq3mrXmV3pBMBURuzmQ0/BmpojlpGFQ7oognJbo0V5rrJRpAw
      v3/6MODPBfT5IJKTpvMK5BcjlDUtmODzm8L0sxI3Ixu0hPy1C6h7ggEs5Lmh
      HyD6rDaECTZMFbCr6sS+uXfMpYp6WXZs4Gx6Kd7PxOwzPELyi0o='
  - secure: ! 'VZoqYL5jbFRJbCxalDno8KuWaQ3HSfPD5usQAPqd2thVrb40R4MX5DxlkXGi
      d6a00585yjomwIuan/UhP8GkUEJ4ZrQBUAP90V4KvvpES7sgi83ecsv8cc3p
      qiFidF9K5eKVk5izylQTOHdFkk0+i44LzmRYmVHAsIhKV/hi+BY='
  matrix:
  - ROBOT_BROWSER=firefox
  - ROBOT_BROWSER=internetexplorer
  - ROBOT_BROWSER=chrome
