---
language: python
python: '2.7'

install:
# Download Sauce Connect:
- curl -O http://saucelabs.com/downloads/Sauce-Connect-latest.zip
- unzip Sauce-Connect-latest.zip
# Start Sauce Connect:
- java -jar Sauce-Connect.jar $SAUCE_USERNAME $SAUCE_ACCESS_KEY -f CONNECTED &
- JAVA_PID=$!
# Buildout Plone:
- mkdir -p buildout-cache/eggs
- mkdir -p buildout-cache/downloads
- python bootstrap.py -c travis.cfg
- bin/buildout -N -t 3 -c travis.cfg

before_script:
# Wait until Sauce has really started:
- bash -c "while [ ! -f CONNECTED ]; do sleep 2; done"
# Configure build variables
- export ROBOT_REMOTE_URL=http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com:80/wd/hub
- export ROBOT_BUILD_NUMBER=travis-$TRAVIS_BUILD_NUMBER
- export ROBOT_BROWSER=internetexplorer
- export ROBOT_DESIRED_CAPABILITIES="platform:Windows 2012,version:10"

script: bin/test

after_script:
# Stop Sauce Connect:
- kill $JAVA_PID

env:
  global:
  - secure: ! 'DQSpUjZK+gjYwthJIr/1mwuck3RpvubMzQdWvM+k0DDRAbIjhn73o/S7p2gh
      OE20DkRV0+g9XrixHHy4wqJhbvGB4SbaQ2MdeDylRwAE2xPOif8+kzMoXlIR
      yLOr3EPKu3vLn64E4FB+KkuZBhsGXD1BATwulc8Qcp6ULiR0i/o='
  - secure: ! 'NJ1vJIH30I3XRdj50mU4wVx4oRa1yBx4x2rjul3qrwxozIpjKEfE7DCxi3w+
      WNjuWKEhP+wRbSLLNC58IMqfKS7ro8RPExClvs2nZhaYhUgzpjIKi6P4xPM+
      FjMoMBzPZGmnFUM+Xx6xw9+fWVwUpec1s8mu03zPCQ1g+8xK8Yw='
